chaekhwajeom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
import books.views
import accounts.views
import chat.views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('',books.views.home,name="home"),
    path('mypage/',accounts.views.mypage,name="mypage"),
    path('registration/edit',accounts.views.edit,name="edit"),
    path('registration/pw_change',accounts.views.pw_change,name="pw_change"),
    path('registration/edit_address', accounts.views.edit_address,name='edit_address'),
    path('book_detail/<int:pk>/delete', books.views.delete, name="delete"),
    path('book_detail/<int:pk>/', books.views.book_detail, name="book_detail"),
    path('like', books.views.like, name='like'),

    path('book_search/',books.views.book_search,name="book_search"),
    path('book_register/',books.views.book_register,name="book_register"),
    
    path('registration/register/', accounts.views.register, name="register"),
    path('accounts/', include('allauth.urls')),
    path('registration/', include('django.contrib.auth.urls')),
    path('registration/login/', auth_views.LoginView.as_view(),{'template_name':'registration/login.html'},name="login"),
    path('registration/logout/', auth_views.LogoutView.as_view(),{'template_name':'registration/logout.html'},name="logout"),
    path('registration/set_address/',accounts.views.set_address,name="set_address"),
    path('registration/socialregister', accounts.views.socialregister, name="socialregister"),
    # path('recovery/pw/', accounts.views.RecoveryPwView.as_view(), name='recovery_pw'),
    path('recovery/recovery_pw', accounts.views.pw_recovery, name='recovery_pw'),
    path('recovery/sendmail', accounts.views.sendmail, name='sendmail'),
    # path('recovery/pw/find/', accounts.views.ajax_find_pw_view, name='ajax_pw'),
    # path('recovery/pw/auth/', accounts.views.auth_confirm_view, name='recovery_auth'),
    # path('recovery/pw/reset/', accounts.views.auth_pw_reset_view, name='recovery_pw_reset'),

    path('chat/',chat.views.chat,name="chat"),
    path('chat/done/<int:sharing_pk>',chat.views.set_sharing_state,name="set_sharing_state"),
    path('chat/chatroom/<int:sharing_pk>',chat.views.chatroom,name="chatroom"),
    path('chat/list_message/<int:pk>',chat.views.message,name="listMessage"),
    # path('chat/list_message/<char:neighbor_pk>/<int:book_pk>/',chat.views.list_message,name="listMessage"),
    path('sharing/<int:book_pk>/<uuid:neighbor_pk>',chat.views.sharing,name="sharing"),
    # re_path(r'^sharing/(?P<neighbor_pk>[0-9a-f\-]{32,})$/(?P<book_pk>[0-9]+)$',chat.views.sharing,name="sharing"),
    # url(r'^sharing/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/(?P<book_pk>[0-9]+)$',chat.views.sharing,name="sharing"),

    path('service/guideline',chat.views.service_guide,name="service_guide"),
    path('report/',chat.views.report,name="report"),
    path('books/service_manual', books.views.service_manual, name= "service_manual"),
    path('books/neighbor_library', books.views.neighbor_library, name = "neighbor_library"),
    path('books/user_library/', books.views.user_library, name="user_library"),
    # path('books/search/newURL',books.views.search,name="pagination"),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

books/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError
from accounts.models import MyUser

# Chaekhwajeom custom Book model manager
class BookManager(models.Manager):
    use_for_related_fields = True

class Book(models.Model):
    objects = BookManager()

    STATUS_CHOICES = (
        ('대여 가능','대여 가능'),
        ('예약 중','예약 중'),
        ('대여 중','대여 중'),
        ('대여 불가능','대여 불가능'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL,related_name="bookuser",on_delete=models.CASCADE,blank=False)
    ISBN = models.CharField(max_length=13,blank=False,verbose_name='ISBN')
    title = models.CharField(max_length=50,verbose_name='도서명')
    author = models.CharField(max_length=30, blank=True,verbose_name="저자")
    publisher = models.CharField(max_length=30,blank=True,verbose_name='출판사')
    status = models.CharField(choices=STATUS_CHOICES,default='대여 가능',max_length=10,verbose_name='상태')
    bookcover = models.URLField(max_length=400,blank=True,verbose_name='표지')
    stored_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'book'
        verbose_name = '도서'
        verbose_name_plural = verbose_name
        ordering = ['-stored_at']

    def __str__(self):
        return f'[{self.user.email}]님의 도서: {self.title}'

    def validate_new_book(isbn,user):
        # 중복 도서 확인
        if Book.objects.filter(ISBN=isbn).exists():
            unique_check = Book.objects.filter(Q(ISBN=isbn) & Q(user=user))
            if unique_check.exists():
                return False, f'{user.nickname}\'ve already registered book [{isbn}]'
        return True

    def delete_book(self):
        self.delete()

    def save(self,*args,**kwargs):
        return super(Book,self).save(*args,**kwargs)

class Review(models.Model):
    book = models.OneToOneField(Book,on_delete=models.CASCADE,primary_key=True)
    book_review=models.TextField(max_length=100,blank=True,verbose_name='리뷰')
    rate=models.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)],default=1,verbose_name='별점')
    likes_user = models.ManyToManyField(settings.AUTH_USER_MODEL,blank=True,related_name='likes_user',verbose_name='좋아요')
    created_date = models.DateTimeField(default=timezone.now)

    class Meta:
        db_table = 'book_review'
        verbose_name = '도서 리뷰'
        verbose_name_plural = verbose_name
        ordering = ['-created_date']

    def count_likes_user(self):
        return self.likes_user.count()

    def __str__(self):
        return f'[{self.book.ISBN}] - {self.book_review[:10]}...'
    

class Comment(models.Model):
    review = models.ForeignKey('Review', on_delete=models.CASCADE)
    review_comment = models.TextField(default='')
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'[{self.review_comment[:10]}...]'
    class Meta:
        db_table = 'neighbor_review'
        verbose_name = '이웃의 리뷰'
        verbose_name_plural = verbose_name
        ordering = ['-created_date']

books/forms.py
from django import forms
from .models import Book, Review, Comment
from .widgets import starWidget

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['status']

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['book_review','rate',]

class ReviewAdminForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['book', 'rate', 'book_review']
        # widgets = {
        #     'rate': starWidget,
        # }
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['review_comment']

books/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.urls import reverse
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

from .models import Book, Review
from accounts.models import MyUser
from chat.models import Message
from .forms import BookForm, ReviewForm, CommentForm

import json,re
from utils.naver_api import search_book_info, register_new_book

def home(request):
    cur_user = request.user
    if request.method == "GET":
        q = request.GET.get('main')
        if q:
            books = Book.objects.filter(Q(title__icontains=q) | Q(author__icontains=q) | Q(publisher__icontains=q))
            for book in books:
                title=book.title.split('(')
                book.title = title[0]
            return render(request,'books/main_search.html',{'books':books})

    if cur_user.is_authenticated:
        return render(request,'books/base.html',{'user':cur_user}) 
    else:
        return render(request,'books/base.html') 

def query_book(request):
    if request.method == "GET":
        q = request.GET.get('main')
        if q:
            books = Book.objects.filter(Q(title__icontains=q) | Q(author__icontains=q) | Q(publisher__icontains=q))
            # print(books)
            return render(request,'books/main_search.html',{'books':books})

@login_required()
def edit(request, pk):
    post = get_object_or_404(Book, pk=pk)
    if request.method == "POST":
        form = BookForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now
            post.save()
            return redirect('detail', pk=post.pk)
    else:
        form = BookForm(instance=post)
    return render(request, 'books/edit.html', {'form': form})

@login_required()
def delete(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.user == book.user:
        if book.status == 2:
            messages.error('현재 대여 중인 도서입니다.')
        else:
            book.delete_book()
            messages.info(request,'도서가 삭제되었습니다.')
    else:
        messages.error(request,'잘못된 접근입니다.')
    return redirect('user_library')


@login_required()
def user_library(request):
    user = request.user
    books = Book.objects.filter(user=user)
    for book in books:
        review = get_object_or_404(Review, pk=book)

        title = book.title.split('(')
        book.title = title[0]
        book.review = review
        book.review_rate = range(review.rate)

        return render(request, 'books/user_library.html', {'user': user, 'books': books})
    
    # kwargs값으로 nickname 붙여서 넘기기
    return HttpResponseRedirect(reverse('user_library'))

def book_search(request):
    if request.method == "GET":
        # option = request.GET.get('option')
        q = request.GET.get('query')
        
        if q is None or q == '':
            return render(request,'books/book_search.html')

        # 도서 검색 수행
        search_result = search_book_info(q)
        index = 0
        
        for book in search_result:
            book['title'] = book['title'].split('(')[0]
            # book['option'] = option
            book['index'] = index
            index += 1

        paginator = Paginator(search_result,5)
        page = request.GET.get('page')
        books = paginator.get_page(page)

        book_form = BookForm()
        review_form = ReviewForm()

        return render(request,'books/book_search.html',{'books':books,'book_form':book_form, 'review_form': review_form})

    return redirect('book_search')

@login_required()
@require_POST
def book_register(request):
    user = request.user
    if request.method == "POST":
        isbn = request.POST.get('isbnvalue')        # 도서 ISBN value
        status = request.POST.get('status')         # 도서 대여 상태
        review = request.POST.get('book_review')    # 도서 리뷰
        star_rate = request.POST.get('review-star') # 도서 별점

        state, book = register_new_book(isbn,user)
        print(state)

        if book:
            # 사용자가 선택한 도서 대여 상태 정보를 저장
            book.status = status                        
            book.save()

            new_review = Review.objects.create(
                book = book,
                book_review = review,
                rate = star_rate,
            )
            new_review.save()

            messages.info(request,'도서와 리뷰가 등록되었습니다!')
            return redirect('book_search')

    return HttpResponseRedirect(reverse('book_search'))


def like(request):
    pk = request.POST.get('pk', None)
    posts = get_object_or_404(Review, pk=pk)
    user = request.user
    if posts.likes_user.filter(email=user.email).exists():
        posts.likes_user.remove(user)
        message = '좋아요 취소'
        messages.info(request,'좋아요를 취소하였습니다.')
    else:
        posts.likes_user.add(user)
        message.info(request,'좋아요!')
    context = {'likes_count':posts.count_likes_user(), 'message': message}
    return HttpResponse(json.dumps(context), content_type="application/json")

def book_detail(request, pk):
    book = get_object_or_404(Book, pk=pk)       # 등록된 도서 객체
    
    # 단순 split 말고 정규표현식으로 '()' 내의 제목 추출, book.subtitle 인자로 html에 넘길 것
    book.title = book.title.split('(')[0]   
    # print(book.get_status_display())
    print(book.status) 
    neighbor = book.user

    review = Review.objects.get(book=book)      # 도서에 대한 review 객체
    
    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = review
            comment.text = comment_form.cleaned_data.get("text")
            comment.save()

            comment_form = CommentForm()
    else:
        comment_form = CommentForm()
    
    return render(request,'books/book_detail.html',{
                    'neighbor' : neighbor, 
                    'book': book, 
                    'review':review,
                    'rate':range(review.rate),
                    'rate_blank': range(5-review.rate),
                    'comment_form': comment_form
                    })
  
def service_manual(request):
    return render(request, 'books/service_manual.html')


@login_required()
def neighbor_library(request):
    cur_user = request.user
    result = []
    dong = MyUser.objects.filter(
       dong__icontains=cur_user.dong).exclude(email=cur_user.email)
    for d in dong:                              # 로그인된 사용자와 같은 동에 거주하는 user
        books = d.bookuser.all()
        books_cnt = books.count()
        if books_cnt > 0:
            info = {}
            info['user'] = d
            info['books'] = d.bookuser.all()
            info['books_cnt'] = books_cnt
            result.append(info)

    result.sort(key=lambda x: x['books_cnt'], reverse=True)
    print(result)
    if not result:
        print('noneeeee')
    
    return render(request, 'books/neighbor_library.html', {'neighbor': result})

templates/books/book_search.html
{% extends 'books/base.html' %}
{% load static %}

{% block content %}

<head>
  <link rel="stylesheet" href="{% static 'css/book.css' %}">
  <link rel="stylesheet" href="{% static 'css/book_search.css'%}">
</head>

<script>
  var isbn_value, index;

  var page;
  var newURL;

  var initialRating = 0;
  var starsTotal = 5;
  $(document).on('show.bs.modal', '#bookRegisterModal', function (event) {
    // alert('debug')  //modal 버튼 작동함

    // 모달창에 데이터 넘기기
    var button = $(event.relatedTarget)

    // 도서 등록 시에 'book_register' view로 넘길 전역변수
    isbn_value = button.data('isbn')
    index = button.data('index')

    // var isbn = $('#isbn').text()
    // var isbn_arr = isbn.split(',')
    // var idx = isbn_arr.length - 1

    var modal = $(this)
    modal.find('#modal-hidden-data').val(isbn_value)

  })

  function setPreviouspageUrl() {
    var curURL = window.location.href;
    page_info = curURL.indexOf('page');

    var subURL = curURL.substr(page_info);
    page = Number(subURL.split('=')[1]);

    newURL = subURL;    // page=2인경우 page value없는 url값만 지정

    if (page != 2) {
      page = page - 1   // 이전 page number 지정
      newURL = newURL + '?page=' + page;
    }

    alert(newURL);
    window.location.replace(newURL);
  }
  function setNextpageUrl() {
    var curURL = window.location.href;
    page_info = curURL.indexOf('page');

    // 첫 번째 page인 경우
    if (page_info == -1) {
      newURL = curURL + '?page=2';
    }
    else {
      var subURL = curURL.substr(page_info);
      page = Number(subURL.split('=')[1]) + 1;

      newURL = curURL.substring(0, page_info - 1);
      newURL = newURL + '?page=' + page;
    }
    // alert(newURL);
    window.location.replace(newURL);

    // if(typeof(history.pushState != "undefined")) {
    //   history.pushState(null,null,newURL);
    //   alert('pushstate debug');
    // }
    // else{
    //   window.location.replace(newURL);
    //   alert('replace debug');

    // }
  }

</script>

<div class="modal fade" id="bookRegisterModal" tabindex="-1" role="dialog" aria-labelledby="bookRegisterModalLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-chaekhwajeom" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title name" id="bookRegisterModalLabel" style="display: none;">도서 등록하기</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-chaekhwajeom-body">
        <form method="POST" action="{% url 'book_register' %}">
          <input id="modal-hidden-data" name="isbnvalue" style="display: none;">
          {%csrf_token%}
          <!-- {{book_form.as_p}}
          {{review_form.as_p}} -->

          <div class="status-box">
            <select name="status" id="id_status">
              <option value="" selected="">도서 상태를 선택해주세요</option>
              <option value="0">대여 가능</option>
              <option value="1">예약 중</option>
              <option value="2">대여 중</option>
              <option value="3">대여 불가능</option>
            </select>
          </div>
          <div class="review-textarea">
            <textarea name="book_review" cols="40" rows="10" maxlength="100" id="id_book_review" placeholder="&#10;리뷰를 작성해주세요"></textarea>
          </div>
          <div class="review-star-rate">
            <input type="radio" id="review-star-5" name="review-star" value="5"/>
              <label for="review-star-5">☆</label>
            <input type="radio" id="review-star-4" name="review-star" value="4"/>
              <label for="review-star-4">☆</label>
            <input type="radio" id="review-star-3" name="review-star" value="3"/>
              <label for="review-star-3">☆</label>
            <input type="radio" id="review-star-2" name="review-star" value="2"/>
              <label for="review-star-2">☆</label>
            <input type="radio" id="review-star-1" name="review-star" value="1"/>
              <label for="review-star-1">☆</label>
          </div>

          <button type="submit" class="btn-chaekhwajeom">등록하기</button>
        </form>
      </div>
      <!-- <div class="modal-footer">
      </div> -->
    </div>
  </div>
</div>

<!-- isbn value를 array format으로 저장 (구분자 '|' ) -->
<!-- index에 따라 parameter로 사용 -->
{%if books%}
<div id="isbn" style="display:none">
  {%for book in books%}
  {{book.isbn}},
  {%endfor%}
</div>
<div id="isbn-pk" style="display:none">
  {%for book in books%}
  {{book.index}},
  {%endfor%}
</div>
{%endif%}

<body>
  <div class="book-search-container">
    <div class="search-bar">
      <form method="GET">
        <input type="text" name="query" placeholder="도서 정보를 검색하세요">
        <button class="btn my-2 my-sm-0 btn-search-ver" type="submit" onclick=location.href="{% url 'book_search' %}">
          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor"
            xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
              d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z" />
            <path fill-rule="evenodd"
              d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z" />
          </svg>
        </button>
      </form>
    </div>
    <div class="search-result">
      {%if books%}
      <!-- pagenation previous 작동안함 -->
      <div class="search-and-register">
        {%for book in books%}
        <div class="book-section">
          <div class="button-section-small">
            <button type="button" class="chaekhwajeom-button-small" data-toggle="modal" data-target="#bookRegisterModal"
              data-index="{{book.index}}" data-isbn="{{book.isbn}}">
              <div class="button-text-section">
                <a class="button-text">등록하기</a>
              </div>
            </button>
          </div>
          <div class="book">
            <div class="front">
              <div class="cover" style="background-image: URL({{book.image}}); ">
              </div>
            </div>
          </div>
          <div class="book-info">
            <div id="title">
              <div id="info">제목 </div>
              <div id="info-result">{{book.title}}</div>
            </div>
            <div id="author">
              <div id="info">작가 </div>
              <div id="info-result">{{book.author}}</div>
            </div>
            <div id="publisher">
              <div id="info">출판사 </div>
              <div id="info-result">{{book.publisher}}</div>
            </div>
          </div>
        </div>
        {%endfor%}
        {%if books.has_next%}
        <div class="pagination-container">
          <div class="pagination">
            <button type="button" class="btn-pagination" onclick="setNextpageUrl();">
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-caret-right-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M12.14 8.753l-5.482 4.796c-.646.566-1.658.106-1.658-.753V3.204a1 1 0 0 1 1.659-.753l5.48 4.796a1 1 0 0 1 0 1.506z"/>
              </svg>
            </button>
          </div>
        </div>
        {%endif%}
      </div>


      {%endif%}
    </div>

  </div>
</body>

{% endblock %}

templates/books/main_search.html
{% extends 'books/base.html' %}
{% block content %}
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'css/book.css' %}">
    <link rel="stylesheet" href="{% static 'css/book_search.css' %}">
    <link rel="stylesheet" href="{% static 'css/main_search.css' %}">
</head>

<body>
    <div class="main-search-container">
        {%if books%}
        <div class="book-section">
            {%for book in books%}
            <div class="book-item">
                <div class="book">
                    <div class="front">
                        <div class="cover" style="background-image: URL({{book.bookcover}});" 
                        onclick="location.href='/book_detail/{{book.pk}}';"></div>
                    </div>
                </div>
                <div class="book-info">
                    <div id="neighbor">
                        <div id="neighbor-nickname">🧚🏻‍♂️{{book.user}}&nbsp</div>
                        이웃님의 도서
                        <div id="neighbor-address"><br><br>{{book.user.sido}} {{book.user.sigungu}} {{book.user.dong}}</div>
                    </div>
                    <div id="title">
                        <div id="info">제목 </div>
                        <div id="info-result">{{book.title}}</div>
                      </div>
                      <div id="author">
                        <div id="info">작가 </div>
                        <div id="info-result">{{book.author}}</div>
                      </div> 
                </div>
            </div>
            {%endfor%}
        </div>
        {%else%}
        <div class="empty">
            책화점에는 검색하신 도서가 존재하지 않습니다 :(
        </div>
        {%endif%}
    </div>
</body>
{% endblock %}

templates/books/neighbor_library.html
{% extends 'books/base.html' %}
{% block content %}
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'css/book.css' %}">
    <!-- 밑에 명시한 stylesheet의 css에서 변경된 사항들만 우선 적용됨 -->
    <link rel="stylesheet" href="{% static 'css/neighbor_library.css' %}">
</head>

<body>
    
    <div class="neighbor-library-container">
        {%if neighbor%}
            {%for ne in neighbor%}
            <div class="neighbor">
                <div class="neighbor-info">
                    <h3>{{ne.user.nickname}} 이웃님 </h3>
                    <p>{{ne.user.sido}} {{ne.user.sigungu}} {{ne.user.dong}}</p>
                </div>
                <div class="neighbor-book">
                    {%for book in ne.books%}
                    <div class="book">
                        <div class="front">
                            <div class="cover" style="background-image: URL({{book.bookcover}});"
                                onclick="location.href='/book_detail/{{book.pk}}';">
                            </div>
                        </div>
                    </div>
                    {%endfor%}
                </div>
            </div>
            {%endfor%}
        {%else%}
        <div class="empty">
            {{user.nickname}} 님의 동네에 등록된 서재가 없어요 :(
        </div>
        {%endif%}

    </div>
    
</body>

{% endblock %}

templates/books/service_manual.html
{% extends 'books/base.html' %}
{% block content %}
{% load static %}
    <link rel = "stylesheet" href="{% static 'css/service_manual.css'%}">
    <script src="http://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
    <script>
    function collapseAll() {
        $(".collapsible-header").removeClass(function () {
            return "active";
        });
        $(".collapsible").collapsible({ accordion: true });
        $(".collapsible").collapsible({ accordion: false });
    }
    function expandAll() {
        $(".collapsible-header").addClass("active");
        $(".collapsible").collapsible({ accordion: false });
    }
    </script>

    <div class="service_manual">📣 책화점 서비스 가이드 📣</div>
    <div class="container">
          <a class="open_button" onClick="expandAll();">모두 열기</a>
          <a class="close_button" onClick="collapseAll();">모두 닫기</a>
                <ul class="collapsible" data-collapsible="expandable">
                    <li>
                      <div class="collapsible-header"><i class="mdi-navigation-chevron-right"></i>
                        📖 책장에서 잊혀져 가는 책을 책화점 서재에 등록해주세요
                      </div>
                      <div class="collapsible-body" style="opacity: 0.7;">
                        <p>같은 동(ex. 마포구 대흥동)에 사는 이웃님이 평소 읽어보고 싶었던 책을 가지고 있었을지도 몰라요.</p>
                        <p>인생책을 빌려주고, 이웃의 반응을 확인해본다면 더욱 멋진 독서 경험이 될지도 모르잖아요?</p>
                      </div>
                    </li>
                    <li>
                      <div class="collapsible-header"><i class="mdi-navigation-chevron-right"></i>
                        📖 주소를 등록하면 주변 이웃들의 책을 우선적으로 보여줘요
                      </div>
                      <div class="collapsible-body" style="opacity: 0.7;">
                        <p>같은 동을 등록한 이웃들의 서재를 우선적으로 보여주어, 관심 있는 책을 보유한 이웃에게 채팅을 신청해보세요.
                        <p>도서관에서 책꽂이 사이사이를 거닐다 우연히 집어들었던 책이 인생책이 된 경험 있으신가요?</p>
                        <p>책화점은 이제 이웃들의 책장에 꽂혀 있는 수많은 책들을 모아서 회원님에게 커다란 도서관을 만들어 드릴 계획이에요.</p>
                      </div>
                    </li>
                    <li>
                      <div class="collapsible-header"><i class="mdi-navigation-chevron-right"></i>
                        📖 불량 유저를 신고해주세요
                      </div>
                      <div class="collapsible-body" style="opacity: 0.7;">
                        <p>이웃에게 책을 빌려주었는데, 책이 훼손되어 돌아왔나요 ㅠ.ㅠ</p>
                        <p>회원님의 마음을 아프게 해드려 너무 죄송합니다.</p>
                        <p>신고해주시면, 커뮤니티 매니저가 즉시 확인하여 정의의 심판을 내려드리겠습니다!</p>
                      </div>
                    </li>
                </ul>
    </div>

  
{% endblock %}

templates/books/tag_detail.html
{% extends 'books/base.html' %}
{% block content %}
{% load static %}
{% endblock %}
<h1># {{tag}} </h1>
<h3>해시태그를 포함한 게시글 {{tag_posts.count}}개</h3> <div class="posts">
    {% for post in tag_posts %}
<a>{{ post.title }} </a>
<br><br>
    {% endfor %}
</div>