chaekhwajeom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
import books.views
import accounts.views
import chat.views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('',books.views.home,name="home"),
    path('mypage/',accounts.views.mypage,name="mypage"),
    path('registration/edit',accounts.views.edit,name="edit"),
    path('registration/pw_change',accounts.views.pw_change,name="pw_change"),
    path('registration/edit_address', accounts.views.edit_address,name='edit_address'),
    path('book_detail/<int:pk>/delete', books.views.delete, name="delete"),
    path('book_detail/<int:pk>/', books.views.book_detail, name="book_detail"),
    path('like', books.views.like, name='like'),

    path('book_search/',books.views.book_search,name="book_search"),
    path('book_register/',books.views.book_register,name="book_register"),
    
    path('registration/register/', accounts.views.register, name="register"),
    path('accounts/', include('allauth.urls')),
    path('registration/', include('django.contrib.auth.urls')),
    path('registration/login/', auth_views.LoginView.as_view(),{'template_name':'registration/login.html'},name="login"),
    path('registration/logout/', auth_views.LogoutView.as_view(),{'template_name':'registration/logout.html'},name="logout"),
    path('registration/set_address/',accounts.views.set_address,name="set_address"),
    path('registration/socialregister', accounts.views.socialregister, name="socialregister"),
    # path('recovery/pw/', accounts.views.RecoveryPwView.as_view(), name='recovery_pw'),
    path('recovery/recovery_pw', accounts.views.pw_recovery, name='recovery_pw'),
    path('recovery/sendmail', accounts.views.sendmail, name='sendmail'),
    # path('recovery/pw/find/', accounts.views.ajax_find_pw_view, name='ajax_pw'),
    # path('recovery/pw/auth/', accounts.views.auth_confirm_view, name='recovery_auth'),
    # path('recovery/pw/reset/', accounts.views.auth_pw_reset_view, name='recovery_pw_reset'),

    path('chat/',chat.views.chat,name="chat"),
    path('chat/done/<int:sharing_pk>',chat.views.set_sharing_state,name="set_sharing_state"),
    path('chat/chatroom/<int:sharing_pk>',chat.views.chatroom,name="chatroom"),
    path('chat/list_message/<int:pk>',chat.views.message,name="listMessage"),
    # path('chat/list_message/<char:neighbor_pk>/<int:book_pk>/',chat.views.list_message,name="listMessage"),
    path('sharing/<int:book_pk>/<uuid:neighbor_pk>',chat.views.sharing,name="sharing"),
    # re_path(r'^sharing/(?P<neighbor_pk>[0-9a-f\-]{32,})$/(?P<book_pk>[0-9]+)$',chat.views.sharing,name="sharing"),
    # url(r'^sharing/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/(?P<book_pk>[0-9]+)$',chat.views.sharing,name="sharing"),

    path('service/guideline',chat.views.service_guide,name="service_guide"),
    path('report/',chat.views.report,name="report"),
    path('books/service_manual', books.views.service_manual, name= "service_manual"),
    path('books/neighbor_library', books.views.neighbor_library, name = "neighbor_library"),
    path('books/user_library/', books.views.user_library, name="user_library"),
    # path('books/search/newURL',books.views.search,name="pagination"),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models
from django.utils import timezone
from books.models import Book
from django.conf import settings

class Sharing(models.Model):
    book = models.OneToOneField(Book,on_delete=models.CASCADE)
    userA = models.ForeignKey(settings.AUTH_USER_MODEL,related_name="userA",on_delete=models.CASCADE)    #현재 유저
    userB = models.ForeignKey(settings.AUTH_USER_MODEL,related_name="userB",on_delete=models.CASCADE)    #이웃
    isFinished = models.BooleanField(default=False)

    def __str__(self):
        return str(self.book)

class Message(models.Model):
    sharing = models.ForeignKey(Sharing,on_delete=models.CASCADE)
    sender = models.ForeignKey(settings.AUTH_USER_MODEL,related_name="sender",on_delete=models.CASCADE, null = True)
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL,related_name="receiver",on_delete=models.CASCADE, null=True)
    sentAt = models.DateTimeField(auto_now_add=True)
    content = models.TextField(max_length=100)
    
    sender_isRead = models.BooleanField(default=False)
    receiver_isRead = models.BooleanField(default=False)

    objects = models.Manager()

    def save(self,**kwargs):
        if not self.id:
            self.sendAt = timezone.now()
        super(Message, self).save(**kwargs)


    class Meta:
        ordering = ['sentAt']
    
    def __str__(self):
        return self.content[:20]

class Report(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    report1 = models.BooleanField('책을 훼손해서 반납했어요',default=False)
    report2 = models.BooleanField('책을 반납하지 않아요(잠수, 연락 안받기 etc)',default=False)
    report3 = models.BooleanField('불량채팅을 했어요(나쁜 말, 못된 말 etc)',default=False)

    content = models.TextField(max_length=200,blank=True)

    def summary(self):
        return self.content[:20]

chat/forms.py
from django import forms
from django.forms import ModelChoiceField
from .models import Message, Report
from accounts.models import MyUser

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['content']
        widgets = {
            'content': forms.Textarea(
                attrs = {
                    'class': 'form-control',
                    'placeholder': '메세지를 작성해주세요',
                }
            )
        }

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ['user','report1','report2','report3','content']

chat/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.http import HttpResponse
from django.db.models import Q
from utils.slack import slack_notify

from .models import Message, Report, Sharing
from .forms import MessageForm, ReportForm
from accounts.models import MyUser
from books.models import Book


def chat(request):
    user = request.user

    # 현 사용자와 거래 내역이 있는 user로만!
    # all_user = MyUser.objects.all().exclude(pk=user.pk)
    # nested list (list > dict > list)
    # ongoing = [
    #     { 
    #         'username': ,
    #         'sharing_info': list( dict {pk, book_title}),
    #     },
    #         ...
    # ]
    sharing = Sharing.objects.filter(Q(userA=user)|Q(userB=user))
    if sharing == None:
        return render(request,'chat/chat.html',{'user':user})

    ongoing = list()
    finished = list()

    all_user = dict()

    for s in sharing:
        if s.userA == user:
            username = s.userB.nickname
            all_user[s.userB.pk] = username
        else:
            username = s.userA.nickname
            all_user[s.userA.pk] = username

        s.book.title = s.book.title.split('(')[0]

        new_neighbor = True
        # 거래 중인 도서 (ongoing)
        if s.isFinished == False:
            for item in ongoing:
                if item['username'] == username:
                    # list에 존재하는 요소인 경우, book list를 append
                    new_neighbor = False
                    item['sharing_info'].append(
                        {s.pk : s.book}
                    )

        # 거래 완료된 도서 (finished)
        else:
            for item in finished:
                if item['username'] == username:
                    new_neighbor = False
                    item['sharing_info'].append(
                        {s.pk : s.book}
                    )

        # list에 존재하지 않던 요소인 경우, 새로운 항목을 append
        if new_neighbor == True:
            sharing_info = list()
            sharing_info.append(
                {s.pk : s.book}
            )

            chat = dict()
            chat['username'] = username
            chat['sharing_info'] = sharing_info
            
            if s.isFinished == False:
                ongoing.append(chat)
            else:
                finished.append(chat)
               
    # print(ongoing)
    # print(finished)
    # for item in finished:
    #     for i in item['sharing_info']:
    #         for key,value in i.items():
    #             print(type(key))
    #             print(value)
    #             print(type(value))

    report_form = ReportForm()

    print(all_user)
    return render(request,'chat/chat.html',{'sharing':'True','ongoing':ongoing, 'finished':finished,'all_user':all_user,'report_form':report_form})

def sharing(request,book_pk,neighbor_pk):
    
    user = request.user
    neighbor = get_object_or_404(MyUser,pk=neighbor_pk)
    book = get_object_or_404(Book,pk=book_pk)

    try:
        q1 = Sharing.objects.get(Q(userA=user)&Q(userB=neighbor)&Q(book=book))
    except Sharing.DoesNotExist:
        q1 = None
        
    try:
        q2 = Sharing.objects.get(Q(userB=user)&Q(userA=neighbor)&Q(book=book))
    except Sharing.DoesNotExist:
        q2 = None

    if q1:
        if q1.isFinished == False:
                print('거래 중인 도서입니다')
        else:
            q1.isFinished = False
            print('거래가 완료된 도서입니다')
        return redirect('chat')

    elif q2:
        if q2.isFinished == False:
                print('거래 중인 도서입니다')
        else:
            q2.isFinished = False
            print('거래가 완료된 도서입니다')
        return redirect('chat')
        
    else:
        sharing = Sharing.objects.create(
            userA = user,
            userB = neighbor,
            book = book,
            isFinished = False
        )
        return redirect('listMessage',sharing.pk)

def set_sharing_state(request,sharing_pk):
    sharing = get_object_or_404(Sharing,pk=sharing_pk)

    if sharing.isFinished == False:
        sharing.isFinished = True
        sharing.save()
        return redirect('chat')

    return redirect('chat')

def chatroom(request,sharing_pk):
    # 채팅 메인페이지에서 채팅 페이지로 이동
    print(sharing_pk)
    
    sharing = get_object_or_404(Sharing,pk=sharing_pk)
    message_list = Message.objects.filter(sharing=sharing)
    received = message_list.filter(receiver=request.user)
    for r in received:
        r.receiver_isRead = True
        r.save()

    return redirect('listMessage',sharing_pk)

def message(request,pk):
    # 채팅방에 접속하면, 
    # 내가 마지막으로 전송한 메세지 이전의 메세지들을 모두 읽음 처리
    
    cur_user = request.user
    sharing = Sharing.objects.get(pk=pk)
    if sharing.userA == cur_user:
        receiver = sharing.userB.nickname
    else:
        receiver = sharing.userA.nickname

    message_list = Message.objects.filter(sharing=sharing)          # 메세지 log

    received = message_list.filter(receiver=request.user)   # 받은 메세지
    sent = message_list.filter(sender=request.user)         # 보낸 메세지

    form = MessageForm()
    if request.method == 'POST':
        content = request.POST.get('content')

        message = Message.objects.create(
            sharing = sharing,
            sender = cur_user,
            content = content,
            receiver_isRead = False,
            sender_isRead = True
        )
        if sharing.userA == cur_user:
            message.receiver = sharing.userB
        else:
            message.receiver = sharing.userA
        message.save()

    return render(request,'chat/message.html',{'messages':message_list,'receiver': receiver, 'form':form})


def chat_guide(request):
    return render(request,'report/chat_guideline.html')

def service_guide(request):
    return render(request,'report/service_guideline.html') 


def report(request):
    if request.method == 'POST':
        report_user_pk = request.POST.get('user')
        report1 = request.POST.get('report1')
        report2 = request.POST.get('report2')
        report3 = request.POST.get('report3')
        content = request.POST.get('content')

        report_user = get_object_or_404(MyUser,pk=report_user_pk)
        print(report_user.nickname)
        if report1 == None:
            report1 = False
        if report2 == None:
            report2 = False
        if report3 == None:
            report3 = False

        report = Report.objects.create(
            user = report_user,
            report1 = report1,
            report2 = report2,
            report3 = report3,
            content = content
        )
        # slack에 신고 접수 알림 보내기
        attachments = [{
            "color": "#FF0000",
            "title": "신고접수 알림",
            "text": "{}".format(report.content)
            }]
        slack_message = "[신고접수] {}에 대한 신고가 접수되었습니다.".format(report_user.nickname)
        slack_notify(slack_message,"#random",username='신고 접수봇',attachments=attachments)

        return redirect('chat')

templates/chat/chat.html
{% extends 'books/base.html' %}
{% block content %}
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'css/book.css' %}">
    <link rel="stylesheet" href="{% static 'css/chat.css' %}">
</head>

<body>
    <div class="modal fade" id="reportModal" tabindex="-1" role="dialog" aria-labelledby="reportModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="reportModalLabel">신고 접수하기</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="modal-report">
                        <form method="POST" action="{% url 'report' %}">
                            {%csrf_token%}
                            <div class="report-username">
                                <select name="user" required="" id="id_user">
                                    <option value="" selected="">신고할 이웃을 선택해주세요</option>
                                    {%for key, value in all_user.items%}
                                    <option value="{{key}}">{{value}}</option>
                                    {%endfor%}
                                </select>
                            </div>
                            
                            <div class="report-checkbox">
                                <div id="checkbox">
                                    <input type="checkbox" name="report1" id="id_report1" value="True"/>
                                    <label for="id_report1">책을 훼손해서 반납했어요 </label>
                                </div>
                                <div id="checkbox">
                                    <input type="checkbox" name="report2" id="id_report2" value="True"/>
                                    <label for="id_report2">책을 반납하지 않아요(잠수, 연락 안받기 etc) </label><br>
                                </div>
                                <div id="checkbox">
                                    <input type="checkbox" name="report3" id="id_report3" value="True"/>
                                    <label for="id_report3">불량채팅을 했어요(나쁜 말, 못된 말 etc) </label>
                                </div>

                            </div>

                            <div class="report-content">
                                <textarea name="content" cols="20" rows="10" maxlength="100" id="id_content" placeholder="&#10;신고 내용을 입력해주세요"></textarea>
                            </div>
                            <button type="submit" class="btn-report">신고할래요 😡</button>
                        </form>
                    </div>
                </div>
                <!-- <div class="modal-footer">
                </div> -->
            </div>
        </div>
    </div>

    <div class="chat-container">
        <div class="chat-alert">
            <!-- notify modal -->
            <button type="button" class="chat-alert-ver" data-toggle="modal" data-target="#reportModal">
                <div class="button-text-section">
                    <svg width="1.0625em" height="1em" viewBox="0 0 17 16" class="bi bi-exclamation-triangle-fill"
                        fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 5zm.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z" />
                    </svg>
                </div>
            </button>
        </div>
        {%if sharing%}
        <div class="chat-list">
            {%if ongoing%}
            <div class="chat-ongoing">
                {%for chat in ongoing%}
                <div class="ongoing-finished-info">
                    <div id="neighbor-name">{{chat.username}} 이웃님</div>
                    <div class="neighbor-book-section">
                        {%for s in chat.sharing_info%}
                        <div class="neighbor-book">
                            {%for key,value in s.items%}
                            <div class="book-thumbnail">
                                <div class="book">
                                    <div class="front">
                                        <div class="cover" style="background-image: URL({{value.bookcover}});"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="book-info">
                                <div id="title">
                                    <div id="info-result">{{value.title}}</div>
                                </div>
                                <div id="book-status" onclick="location.href='{% url 'chatroom' sharing_pk=key %}';">
                                    <div id="book-status-button">
                                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-left-right"
                                        fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd"
                                            d="M1 11.5a.5.5 0 0 0 .5.5h11.793l-3.147 3.146a.5.5 0 0 0 .708.708l4-4a.5.5 0 0 0 0-.708l-4-4a.5.5 0 0 0-.708.708L13.293 11H1.5a.5.5 0 0 0-.5.5zm14-7a.5.5 0 0 1-.5.5H2.707l3.147 3.146a.5.5 0 1 1-.708.708l-4-4a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 4H14.5a.5.5 0 0 1 .5.5z" />
                                    </svg>
                                    진행중
                                    </div>
                                </div>
                                <div id="book-status-change" onclick="location.href='{% url 'set_sharing_state' sharing_pk=key %}'">
                                    <div id="book-status-change-button">완료</div>
                                </div>
                            </div>
                            {%endfor%}
                        </div>
                        {%endfor%}
                    </div>
                </div>
                {%endfor%}
            </div>
            {%endif%}
            {%if finished%}
            <div class="chat-finished">
                {%for chat in finished%}
                <div class="ongoing-finished-info">
                    <div id="neighbor-name">{{chat.username}} 이웃님</div>
                    <div class="neighbor-book-section">
                        {%for s in chat.sharing_info%}
                        <div class="neighbor-book">
                            {%for key,value in s.items%}
                            <div class="book-thumbnail">
                                <div class="book">
                                    <div class="front">
                                        <div class="cover" style="background-image: URL({{value.bookcover}});"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="book-info">
                                <div id="title">
                                    <div id="info-result">{{value.title}}</div>
                                </div>
                                <div id="book-status" onclick="location.href='{% url 'chatroom' sharing_pk=key %}';">
                                    <div id="book-status-button">
                                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-check2-all"
                                        fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd"
                                            d="M12.354 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z" />
                                        <path
                                            d="M6.25 8.043l-.896-.897a.5.5 0 1 0-.708.708l.897.896.707-.707zm1 2.414l.896.897a.5.5 0 0 0 .708 0l7-7a.5.5 0 0 0-.708-.708L8.5 10.293l-.543-.543-.707.707z" />
                                    </svg>
                                    진행완료
                                    </div>
                                </div>
                            </div>
                            {%endfor%}
                        </div>
                        {%endfor%}
                    </div>
                </div>
                {%endfor%}
            </div>
            {%endif%}
        </div>
        {%else%}
        <div class="empty">
            {{user.nickname}} 님! 아직 진행 중인 거래가 없으시네요! :(
        </div>
        {%endif%}
    </div>
</body>

{% endblock %}

templates/chat/message.html
{% extends 'books/base.html' %}
{% block content %}
{% load static %}

<head>
    <!-- <link rel="stylesheet" href="{% static 'css/book.css' %}"> -->
    <link rel="stylesheet" href="{% static 'css/message.css' %}">
</head>

<body>
        <div class="chat-room">
            <div id="list-message">
                <div id="list-title">
                    <h2>📩 {{receiver}}님과의 채팅 📩</h2>
                </div>
                <div id="message-log">
                    {%for message in messages%}
                    <p>{{message.sender}} (이)가 {{message.receiver}}에게 : {{message.content}}</p>
                    {%endfor%}
                </div>
            </div>
            <div id="send-message">
                <div id="send-title">
                    <h2>📩</h2>
                    <form method="POST">
                        {%csrf_token%}
                        <textarea name="content" cols="40" rows="10" class="form-control" placeholder="메세지를 작성해주세요" maxlength="100" required="" id="id_content"></textarea>
                    <div class="send-action">
                        <!-- <p onclick="this.form.submit()">전송하기</p> -->
                        <input type="submit" value="전송하기"/>
                    </div>
                </form>
    
                </div>
            </div>
        </div>
    </div>


    
{% endblock %}